# Generated by Django 5.1.15 on 2026-08-05 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_farm_electrical_conductivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('growth_stage', models.CharField(default='Basal / Sowing', max_length=100)),
                ('recommendation_type', models.CharField(choices=[('SOIL_BASED', 'Soil-Based High Accuracy Recommendation'), ('ESTIMATED', 'Estimated Recommendation')], default='SOIL_BASED', max_length=20)),
                ('confidence_score', models.FloatField(help_text='Confidence percentage (e.g. 92.5)')),
                ('recommended_fertilizer', models.CharField(max_length=150)),
                ('dosage_per_acre_kg', models.FloatField(help_text='Recommended dosage per acre in kg')),
                ('total_quantity_kg', models.FloatField(help_text='Total fertilizer quantity required for farm area')),
                ('estimated_cost_inr', models.FloatField(help_text='Estimated cost in INR (Rupees)')),
                ('price_per_kg_inr', models.FloatField(default=0.0)),
                ('nitrogen', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('soil_ph', models.FloatField(blank=True, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('nutrient_analysis', models.JSONField(default=dict, help_text='Deficit comparison matrix (N, P, K, pH)')),
                ('application_schedule', models.JSONField(default=list, help_text='Split application timeline (Day 1, Day 15, Day 30)')),
                ('alternative_fertilizers', models.JSONField(default=list, help_text='Ranked alternative options with explanations')),
                ('weather_snapshot', models.JSONField(default=dict, help_text='Weather status, rain/wind warnings')),
                ('safety_warnings', models.JSONField(default=list, help_text='Agricultural safety handling guidelines')),
                ('ai_explanation', models.TextField(help_text='Scientifically explainable reasoning for farmer')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Application'), ('APPLIED', 'Applied to Farm')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_recommendations', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
