# Generated by Django 5.1.15 on 2026-08-07 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm_electrical_conductivity_and_more'),
        ('fertilizer_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizerrecommendationhistory',
            name='cost_summary',
            field=models.JSONField(default=dict, help_text='Itemized cost summary and grand total'),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendationhistory',
            name='nutrient_gap',
            field=models.JSONField(default=dict, help_text='Calculated nutrient deficit matrix'),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendationhistory',
            name='nutrient_requirement',
            field=models.JSONField(default=dict, help_text='Crop nutrient requirements breakdown'),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendationhistory',
            name='protection_plan',
            field=models.JSONField(default=dict, help_text='Weed, disease, pest, and micronutrient protection measures'),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendationhistory',
            name='ai_explanation',
            field=models.TextField(blank=True, default='', help_text='Scientifically explainable reasoning for farmer'),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendationhistory',
            name='alternative_fertilizers',
            field=models.JSONField(default=list, help_text='Top candidate fertilizer plans'),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendationhistory',
            name='application_schedule',
            field=models.JSONField(default=list, help_text='Split application timeline'),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendationhistory',
            name='confidence_score',
            field=models.FloatField(default=90.0, help_text='Confidence percentage (e.g. 92.5)'),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendationhistory',
            name='dosage_per_acre_kg',
            field=models.FloatField(default=0.0, help_text='Recommended dosage per acre in kg'),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendationhistory',
            name='estimated_cost_inr',
            field=models.FloatField(default=0.0, help_text='Estimated cost in INR (Rupees)'),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendationhistory',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_recommendations', to='farms.farm'),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendationhistory',
            name='total_quantity_kg',
            field=models.FloatField(default=0.0, help_text='Total fertilizer quantity required for farm area'),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendationhistory',
            name='weather_snapshot',
            field=models.JSONField(default=dict, help_text='Weather status and advisories'),
        ),
    ]
