# Generated by Django 6.0.4 on 2026-08-02 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_farm_electrical_conductivity_and_more'),
        ('recommendation', '0002_remove_recommendationhistory_feature_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketForecastHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('best_market', models.CharField(max_length=255)),
                ('best_modal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('markets_data', models.JSONField(default=list)),
                ('forecast_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trend', models.CharField(blank=True, max_length=50, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('forecast_source', models.CharField(default='MarketEngine_V1', max_length=100)),
                ('api_source', models.CharField(default='data.gov.in', max_length=100)),
                ('resource_id', models.CharField(default='9ef84268-d588-465a-a308-a864a43d0070', max_length=255)),
                ('api_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_forecasts', to='farms.farm')),
                ('recommendation_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_forecasts', to='recommendation.recommendationhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
