# Generated by Django 6.0.4 on 2026-08-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketforecasthistory',
            name='analytics_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='marketforecasthistory',
            name='market_health_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketforecasthistory',
            name='opportunity_score',
            field=models.IntegerField(default=0),
        ),
    ]
