# Generated by Django 6.0.4 on 2026-08-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_forecast', '0002_marketforecasthistory_analytics_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketforecasthistory',
            name='market_health_index',
        ),
        migrations.RemoveField(
            model_name='marketforecasthistory',
            name='opportunity_score',
        ),
    ]
