# Generated by Django 6.0.3 on 2026-08-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_forecast', '0003_remove_marketforecasthistory_market_health_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=255)),
                ('current_price', models.JSONField(default=dict)),
                ('weekly_price_history', models.JSONField(default=list)),
                ('monthly_price_history', models.JSONField(default=list)),
                ('yearly_price_history', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('api_provider', models.CharField(default='data.gov.in', max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['crop', 'state', 'district', 'market'], name='market_fore_crop_036728_idx')],
                'unique_together': {('crop', 'state', 'district', 'market')},
            },
        ),
    ]
