# Generated by Django 5.1.15 on 2026-08-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_forecast', '0004_marketcache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketcache',
            options={'verbose_name': 'Market Cache', 'verbose_name_plural': 'Market Caches'},
        ),
        migrations.RemoveIndex(
            model_name='marketcache',
            name='market_fore_crop_036728_idx',
        ),
        migrations.AlterField(
            model_name='marketcache',
            name='api_provider',
            field=models.CharField(default='data.gov.in', max_length=50),
        ),
        migrations.AlterField(
            model_name='marketcache',
            name='current_price',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='marketcache',
            name='market',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='marketcache',
            name='monthly_price_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='marketcache',
            name='weekly_price_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='marketcache',
            name='yearly_price_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
