# Generated by Django 6.0.7 on 2026-08-04 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_farm_electrical_conductivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weather', models.JSONField(blank=True, null=True)),
                ('yesterday_hourly_forecast', models.JSONField(blank=True, null=True)),
                ('today_hourly_forecast', models.JSONField(blank=True, null=True)),
                ('weekly_hourly_forecast', models.JSONField(blank=True, null=True)),
                ('daily_forecast', models.JSONField(blank=True, null=True)),
                ('current_updated_at', models.DateTimeField(blank=True, null=True)),
                ('today_updated_at', models.DateTimeField(blank=True, null=True)),
                ('weekly_updated_at', models.DateTimeField(blank=True, null=True)),
                ('daily_updated_at', models.DateTimeField(blank=True, null=True)),
                ('api_provider', models.CharField(default='open-meteo', max_length=50)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_cache', to='farms.farm')),
            ],
        ),
    ]
