# Generated by Django 6.0.4 on 2026-08-01 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_farm_electrical_conductivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_crop', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('season', models.CharField(max_length=50)),
                ('weather_snapshot', models.JSONField(help_text='Stores temperature, humidity, rainfall, wind_speed, pressure, description, cloud_cover')),
                ('feature_snapshot', models.JSONField(help_text='Stores ML input: nitrogen, phosphorus, potassium, soil_ph, temperature, humidity, rainfall, season')),
                ('prediction_source', models.CharField(default='Dummy', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
