# Generated by Django 6.0.3 on 2026-08-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='feature_snapshot',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='season',
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='expected_yield',
            field=models.FloatField(blank=True, help_text='Expected yield in kg/ha', null=True),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='explanation',
            field=models.JSONField(blank=True, default=list, help_text='List of key reasons explaining why the crop was recommended'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='input_values',
            field=models.JSONField(blank=True, default=dict, help_text='Stores input soil values (N, P, K, pH, water_requirement) and requested comparison crops'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='recommendation_mode',
            field=models.CharField(choices=[('AI', 'AI Recommendation (With Soil Test Report)'), ('Quick', 'Quick Recommendation (No Soil Test Report)')], default='AI', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='recommendation_type',
            field=models.CharField(choices=[('BEST', 'Recommend Best Crop'), ('COMPARE', 'Compare Selected Crops')], default='BEST', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='results_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Complete structured prediction and comparison output'),
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='Confidence percentage'),
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='prediction_source',
            field=models.CharField(default='ML Model', max_length=100),
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='weather_snapshot',
            field=models.JSONField(default=dict, help_text='Stores 7-day temp avg, 7-day humidity avg, 7-day cumulative rainfall, description'),
        ),
    ]
