# Generated by Django 6.0.4 on 2026-08-01 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='electrical_conductivity',
            field=models.FloatField(blank=True, help_text='Electrical Conductivity in dS/m', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='last_soil_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='nitrogen',
            field=models.FloatField(blank=True, help_text='Nitrogen (N) content in kg/ha', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(200.0)]),
        ),
        migrations.AddField(
            model_name='farm',
            name='organic_carbon',
            field=models.FloatField(blank=True, help_text='Organic Carbon percentage', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='phosphorus',
            field=models.FloatField(blank=True, help_text='Phosphorus (P) content in kg/ha', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(200.0)]),
        ),
        migrations.AddField(
            model_name='farm',
            name='potassium',
            field=models.FloatField(blank=True, help_text='Potassium (K) content in kg/ha', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(300.0)]),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_ph',
            field=models.FloatField(blank=True, help_text='Soil pH value', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)]),
        ),
    ]
