# Generated by Django 5.1.15 on 2026-08-07 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm_electrical_conductivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='boron',
            field=models.FloatField(blank=True, help_text='Boron (B) content in ppm', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='farm',
            name='calcium',
            field=models.FloatField(blank=True, help_text='Calcium (Ca) content in kg/ha', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2000.0)]),
        ),
        migrations.AddField(
            model_name='farm',
            name='copper',
            field=models.FloatField(blank=True, help_text='Copper (Cu) content in ppm', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='farm',
            name='iron',
            field=models.FloatField(blank=True, help_text='Iron (Fe) content in ppm', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(200.0)]),
        ),
        migrations.AddField(
            model_name='farm',
            name='magnesium',
            field=models.FloatField(blank=True, help_text='Magnesium (Mg) content in kg/ha', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AddField(
            model_name='farm',
            name='manganese',
            field=models.FloatField(blank=True, help_text='Manganese (Mn) content in ppm', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(200.0)]),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_moisture',
            field=models.FloatField(blank=True, help_text='Soil Moisture percentage', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='sulphur',
            field=models.FloatField(blank=True, help_text='Sulphur (S) content in kg/ha', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
        migrations.AddField(
            model_name='farm',
            name='zinc',
            field=models.FloatField(blank=True, help_text='Zinc (Zn) content in ppm', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='farm',
            name='nitrogen',
            field=models.FloatField(blank=True, help_text='Nitrogen (N) content in kg/ha', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AlterField(
            model_name='farm',
            name='phosphorus',
            field=models.FloatField(blank=True, help_text='Phosphorus (P) content in kg/ha', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AlterField(
            model_name='farm',
            name='potassium',
            field=models.FloatField(blank=True, help_text='Potassium (K) content in kg/ha', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
    ]
