# Generated by Django 5.1.15 on 2026-08-05 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_farm_electrical_conductivity_and_more'),
        ('recommendation', '0002_remove_recommendationhistory_feature_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('farm_area', models.FloatField()),
                ('area_unit', models.CharField(default='Acre', max_length=20)),
                ('expected_yield_total', models.FloatField(help_text='Total yield in Quintals')),
                ('predicted_market_price', models.FloatField(help_text='Predicted 3-month harvest price in INR/Quintal')),
                ('cost_breakdown', models.JSONField(default=dict, help_text='Individual costs and source info')),
                ('financial_summary', models.JSONField(default=dict, help_text='Gross Income, Net Profit, ROI, Profit Margin, Break-even Price')),
                ('scenarios', models.JSONField(default=dict, help_text='Best, Average, Worst case metrics')),
                ('risk_analysis', models.JSONField(default=dict, help_text='Risk level and risk factors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_analyses', to='farms.farm')),
                ('recommendation_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_analyses', to='recommendation.recommendationhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
